# These are supported funding model platforms

github: paulyhedral sweetrpg # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: sweetrpg # Replace with a single Patreon username
