# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.

name=CatHerder
mod_id=catherder

org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

forge_version=1.19.2-43.3.7
mcp_channel=official
mcp_mappings=1.19.2
parchment_version=2022.11.27-1.19.2
jupiter_version=5.8.1
# for the Apple Silicon plugin
mc_version=1.19.2
base_mc_version=1.19
target_mc_version=1.19.2
additional_mc_versions=1.19

fml_version_range=[43,)
forge_version_range=[43.3.7,)
minecraft_version_range=[1.19.2, 1.19.3)

curseforge_project_id=580311
# TODO: temporary
curseforge_release_type=beta

# JEI
jei_version=11.6.0.1018

# DoggyTalents
dt_version=2.6.10
dt_project_id=271050
dt_file_id=4318535

# DoggyTalentsNext
dtn_version=1.15.0
dtn_project_id=694492
dtn_file_id=4681000

# The One Probe
top_version=8.0.0
top_project_id=245211
top_file_id=4442439

# Patchouli
ptch_version=1.19.4-79.1-FORGE
ptch_file_id=4636289

# Farmer's Delight
fd_file_id=3615366

# Appleskin
appleskin_version=mc1.19.4-2.4.1

# CraftTweaker
crafttweaker_version=9.1.192
crafttweaker_ap_version=3.0.0.8
