modLoader="javafml"
loaderVersion="${fml_version_range}"
license="MIT"
issueTrackerURL="https://github.com/sweetrpg/CatHerder/issues"
displayURL="https://minecraft.curseforge.com/projects/cat-herder/"
logoFile= "../ch_logo.png"
[[mods]] #mandatory
    modId="catherder"
    version="${version}"
    updateJSONURL="https://minecraft.sweetrpg.com/mods/catherder/version.json"
    displayName="Cat Herder"
    credits="paulyhedral,percivalalb,RaustBlackDragon,NovaViper"
    authors="paulyhedral"
    description='''
    Turning your cats into fun, playful cats.
    '''
[[dependencies.catherder]] #optional
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.catherder]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
