# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Data Generation (1.18)

on:
  push:
    branches: [ 1.18 ]
    paths:
      - 'src/main/java/com/sweetrpg/catherder/data/**'
      - build.gradle
      - gradle.properties
  pull_request:
    branches: [ 1.18 ]
    paths:
      - 'src/main/java/com/sweetrpg/catherder/data/**'
      - build.gradle
      - gradle.properties

jobs:
  datagen:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: build prepareCatherder_data --stacktrace
    - name: Commit version file
      run: |
        git config --global user.email "ci@sweetrpg.com"
        git config --global user.name "SweetRPG Data Generator"
        git add src/generated
        git commit -m "Generate data"
        git push origin
